eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:8771/eureka
  instance:
    hostname: localhost

microservice:
  paymentservice:
    endpoints:
      endpoint:
        uri: http://PAYMENT-SERVICE/payments

paymenturl: http://PAYMENT-SERVICE/payments
        
